[package]
name = "scraper-test"
version = "0.1.0"
edition = "2021"

[dependencies]
mockall = "0.13.1"
reqwest = "0.12.12"
scraper = "0.23.1"
sqlx = { version = "0.8.3", features = ["chrono", "sqlite", "runtime-tokio"] }
tokio = { version = "1.43.0", features = ["full"] }
